chat-prefix: "<gradient:#ff0066:#aa0022>AshUtils</gradient>"
head-worth: 100
currency-symbol: $
vanish-on-login-group: vol
join-message: "&a&l+ &r&e{USERNAME}"
quit-message: "&c&l- &r&e{USERNAME}"
xp:
  buy-cost: 2.2
  sell-worth: 2
  maximum-buy: 10000
discord:
  afk-webhook: "PUT APPLICATION/JSON WEBHOOK URL HERE"
  code-webhook: "PUT APPLICATION/JSON WEBHOOK URL HERE"
  mine-webhook: "PUT APPLICATION/JSON WEBHOOK URL HERE"
  report-webhook: "PUT APPLICATION/JSON WEBHOOK URL HERE"
suffix:
  size: 3
  list: ["builder"]
  ontime-reward:
    enabled: true
    name: "grinder"
    reward-time: TIME IN DAYS
pvp:
  worlds: ["testing"]
  kill-prize: 100
  prize-cooldown: 60